<?xml version="1.0" encoding="UTF-8"?><testrun name="ProjetoIssueTeste" project="ProjetoIssues" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testsuite name="com.senac.projetoissues.test.ProjetoIssueTeste" time="0.015">
    <testcase name="initializationError" classname="com.senac.projetoissues.test.ProjetoIssueTeste" time="0.015">
      <error>java.lang.NoClassDefFoundError: LUsuario;&#13;
	at java.lang.Class.getDeclaredFields0(Native Method)&#13;
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)&#13;
	at java.lang.Class.getDeclaredFields(Unknown Source)&#13;
	at org.junit.runners.model.TestClass.&lt;init&gt;(TestClass.java:44)&#13;
	at org.junit.runners.ParentRunner.&lt;init&gt;(ParentRunner.java:73)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.&lt;init&gt;(BlockJUnit4ClassRunner.java:55)&#13;
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:13)&#13;
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)&#13;
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)&#13;
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)&#13;
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.&lt;init&gt;(JUnit4TestReference.java:33)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.&lt;init&gt;(JUnit4TestClassReference.java:25)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:48)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
Caused by: java.lang.ClassNotFoundException: Usuario&#13;
	at java.net.URLClassLoader$1.run(Unknown Source)&#13;
	at java.net.URLClassLoader$1.run(Unknown Source)&#13;
	at java.security.AccessController.doPrivileged(Native Method)&#13;
	at java.net.URLClassLoader.findClass(Unknown Source)&#13;
	at java.lang.ClassLoader.loadClass(Unknown Source)&#13;
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)&#13;
	at java.lang.ClassLoader.loadClass(Unknown Source)&#13;
	... 19 more&#13;
&#13;
</error>
    </testcase>
  </testsuite>
</testrun>
